Kmu.Appointment/Controllers/ContactController.cs
using DevExtreme.AspNet.Mvc.Builders;
using Kmu.Appointment.Models.Entity2;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Kmu.Appointment.Controllers
{
    public class ContactController : BaseController
    {
        
        public ContactController(DbAppointmentContext context) : base(context)
        {
           
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Contact c)
        {
            Context.Contacts.Add(c);
            Context.SaveChanges();

            return RedirectToAction("Index","Home");
        }
    }
}

Kmu.Appointment/Controllers/PatientsController.cs
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Kmu.Appointment.Models.Entity2;

namespace Kmu.Appointment.Controllers
{
    [Route("[controller]/[action]")]
    public class PatientsController : BaseController
    {

        public PatientsController(DbAppointmentContext context) :base(context) {
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Get(DataSourceLoadOptions loadOptions) {
            var patients = Context.Patients.Select(i => new {
                i.Id,
                i.NameSurname,
                i.Tc,
                i.Doctor,
                i.Mail,
                i.Telephone
            });

            

            return Json(await DataSourceLoader.LoadAsync(patients, loadOptions));
        }

        [HttpPost]
        public async Task<IActionResult> Post(string values) {
            var model = new Patient();
            var valuesDict = JsonConvert.DeserializeObject<IDictionary>(values);
            PopulateModel(model, valuesDict);

            if(!TryValidateModel(model))
                return BadRequest(GetFullErrorMessage(ModelState));

            var result = Context.Patients.Add(model);
            await Context.SaveChangesAsync();

            return Json(new { result.Entity.Id });
        }

        [HttpPut]
        public async Task<IActionResult> Put(int key, string values) {
            var model = await Context.Patients.FirstOrDefaultAsync(item => item.Id == key);
            if(model == null)
                return StatusCode(409, "Object not found");

            var valuesDict = JsonConvert.DeserializeObject<IDictionary>(values);
            PopulateModel(model, valuesDict);

            if(!TryValidateModel(model))
                return BadRequest(GetFullErrorMessage(ModelState));

            await Context.SaveChangesAsync();
            return Ok();
        }

        [HttpDelete]
        public async Task Delete(int key) {
            var model = await Context.Patients.FirstOrDefaultAsync(item => item.Id == key);

            Context.Patients.Remove(model);
            await Context.SaveChangesAsync();
        }


        [HttpGet]
        public async Task<IActionResult> DoctorsLookup(DataSourceLoadOptions loadOptions) {
            var lookup = from i in Context.Doctors
                         orderby i.Title
                         select new {
                             Value = i.Id,
                             Text = i.NameSurname
                         };
            return Json(await DataSourceLoader.LoadAsync(lookup, loadOptions));
        }

        private void PopulateModel(Patient model, IDictionary values) {
            string ID = nameof(Patient.Id);
            string NAME_SURNAME = nameof(Patient.NameSurname);
            string TC = nameof(Patient.Tc);
            string DOCTOR = nameof(Patient.Doctor);
            string MAİL = nameof(Patient.Mail);
            string TELEPHONE = nameof(Patient.Telephone);

            if(values.Contains(ID)) {
                model.Id = Convert.ToInt32(values[ID]);
            }

            if(values.Contains(NAME_SURNAME)) {
                model.NameSurname = Convert.ToString(values[NAME_SURNAME]);
            }

            if(values.Contains(TC)) {
                model.Tc = Convert.ToString(values[TC]);
            }

            if(values.Contains(DOCTOR)) {
                model.Doctor = values[DOCTOR] != null ? Convert.ToInt32(values[DOCTOR]) : (int?)null;
            }

            if(values.Contains(MAİL)) {
                model.Mail = Convert.ToString(values[MAİL]);
            }

            if(values.Contains(TELEPHONE)) {
                model.Telephone = Convert.ToString(values[TELEPHONE]);
            }
        }

        private string GetFullErrorMessage(ModelStateDictionary modelState) {
            var messages = new List<string>();

            foreach(var entry in modelState) {
                foreach(var error in entry.Value.Errors)
                    messages.Add(error.ErrorMessage);
            }

            return String.Join(" ", messages);
        }
    }
}

Kmu.Appointment/Controllers/PolyclinicsController.cs
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Kmu.Appointment.Models.Entity2;

namespace Kmu.Appointment.Controllers
{
    [Route("[controller]/[action]")]
    public class PolyclinicsController : BaseController
    {

        public PolyclinicsController(DbAppointmentContext context):base(context) {
        }

        public IActionResult Polyclinics()
        {
            var value = Context.Polyclinics.ToList();
            return View(value);
        }

        [HttpGet]
        public async Task<IActionResult> Get(DataSourceLoadOptions loadOptions) {
            var polyclinics = Context.Polyclinics.Select(i => new {
                i.Id,
                i.Name,
                i.Description
            });

           

            return Json(await DataSourceLoader.LoadAsync(polyclinics, loadOptions));
        }

        [HttpPost]
        public async Task<IActionResult> Post(string values) {
            var model = new Polyclinic();
            var valuesDict = JsonConvert.DeserializeObject<IDictionary>(values);
            PopulateModel(model, valuesDict);

            if(!TryValidateModel(model))
                return BadRequest(GetFullErrorMessage(ModelState));

            var result = Context.Polyclinics.Add(model);
            await Context.SaveChangesAsync();

            return Json(new { result.Entity.Id });
        }

        [HttpPut]
        public async Task<IActionResult> Put(int key, string values) {
            var model = await Context.Polyclinics.FirstOrDefaultAsync(item => item.Id == key);
            if(model == null)
                return StatusCode(409, "Object not found");

            var valuesDict = JsonConvert.DeserializeObject<IDictionary>(values);
            PopulateModel(model, valuesDict);

            if(!TryValidateModel(model))
                return BadRequest(GetFullErrorMessage(ModelState));

            await Context.SaveChangesAsync();
            return Ok();
        }

        [HttpDelete]
        public async Task Delete(int key) {
            var model = await Context.Polyclinics.FirstOrDefaultAsync(item => item.Id == key);

            Context.Polyclinics.Remove(model);
            await Context.SaveChangesAsync();
        }


        private void PopulateModel(Polyclinic model, IDictionary values) {
            string ID = nameof(Polyclinic.Id);
            string NAME = nameof(Polyclinic.Name);
            string DESCRİPTİON = nameof(Polyclinic.Description);

            if(values.Contains(ID)) {
                model.Id = Convert.ToInt32(values[ID]);
            }

            if(values.Contains(NAME)) {
                model.Name = Convert.ToString(values[NAME]);
            }

            if(values.Contains(DESCRİPTİON)) {
                model.Description = Convert.ToString(values[DESCRİPTİON]);
            }
        }

        private string GetFullErrorMessage(ModelStateDictionary modelState) {
            var messages = new List<string>();

            foreach(var entry in modelState) {
                foreach(var error in entry.Value.Errors)
                    messages.Add(error.ErrorMessage);
            }

            return String.Join(" ", messages);
        }
    }
}

Kmu.Appointment/Views/Shared/ProfileLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Purple Admin</title>

    <link rel="stylesheet" href="~/AdminPage/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/AdminPage/assets/vendors/css/vendor.bundle.base.css">

    <link rel="stylesheet" href="~/AdminPage/assets/css/style.css">

    <link rel="shortcut icon" href="~/AdminPage/assets/images/favicon.ico" />
    <link rel="stylesheet" href="~/css/vendor.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Site.css" />
    <script src="~/js/vendor.js" asp-append-version="true"></script>
</head>
<body>
    <div class="container-scroller">
        <!-- partial:../../partials/_navbar.html -->
        <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo" href="../../index.html"><img src="~/AdminPage/assets/images/logo.svg" alt="logo" /></a>
                <a class="navbar-brand brand-logo-mini" href="../../index.html"><img src="~/AdminPage/assets/images/logo-mini.svg" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-stretch">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="mdi mdi-menu"></span>
                </button>
                <div class="search-field d-none d-md-block">
                    <form class="d-flex align-items-center h-100" action="#">
                        <div class="input-group">
                            <div class="input-group-prepend bg-transparent">
                                <i class="input-group-text border-0 mdi mdi-magnify"></i>
                            </div>
                            <input type="text" class="form-control bg-transparent border-0" placeholder="Search projects">
                        </div>
                    </form>
                </div>
                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                            <div class="nav-profile-img">
                                <img src="~/AdminPage/assets/images/faces/face1.jpg" alt="image">
                                <span class="availability-status online"></span>
                            </div>
                            <div class="nav-profile-text">
                                <p class="mb-1 text-black">David Greymaax</p>
                            </div>
                        </a>
                    </li>
                    <li class="nav-item d-none d-lg-block full-screen-link">
                        <a class="nav-link">
                            <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
                        </a>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:../../partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item nav-profile">
                        <a href="#" class="nav-link">
                            <div class="nav-profile-image">
                                <img src="~/AdminPage/assets/images/faces/face1.jpg" alt="profile">
                                <span class="login-status online"></span>
                                <!--change to offline or busy as needed-->
                            </div>
                            <div class="nav-profile-text d-flex flex-column">

                                <span class="font-weight-bold mb-2">Admin</span>


                                <span class="text-secondary text-small">Project Manager</span>
                            </div>
                            <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
                        </a>
                    </li>

                    @if (User.IsInRole(((byte)Kmu.Appointment.Models.Enums.Role.Admin).ToString()))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="DoctorList" asp-action="Index">

                                <span class="menu-title">Doktor Listesi</span>

                                <i class="mdi mdi-contacts menu-icon"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="PolyclinicList" asp-action="Index">
                                <span class="menu-title">Poliklinik Listesi</span>
                                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Patients" asp-action="Index">
                                <span class="menu-title">Hasta Listesi</span>
                                <i class="mdi mdi-chart-bar menu-icon"></i>
                            </a>
                        </li>
         
                    }
                    @if (User.IsInRole(((byte)Kmu.Appointment.Models.Enums.Role.Doctor).ToString()))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="DoctorPatient" asp-action="Index">
                                <span class="menu-title">Hasta Listesi</span>
                                <i class="mdi mdi-contacts menu-icon"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="DoctorCalendar" asp-action="Index">
                                <span class="menu-title">Takvim Görüntüle</span>
                                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="DoctorProfile" asp-action="Index">
                                <span class="menu-title">Profil Düzenle</span>
                                <i class="mdi mdi-chart-bar menu-icon"></i>
                            </a>
                        </li>

                    }
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                            <span class="menu-title">Siteye Git</span>
                            <i class="mdi mdi-car menu-icon"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Login" asp-action="LogOut">
                            <span class="menu-title">Çıkış Yap</span>
                            <i class="mdi mdi-logout-variant menu-icon"></i>
                        </a>
                    </li>

</nav>


            @* @await Html.PartialAsync("~/Views/Profile/AdminNavbarPartial.cshtml")*@

            @* @await Html.PartialAsync("~/Views/Profile/DoctorsNavbarPartial.cshtml")*@


            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()
                </div>

                <footer class="footer">
                    <div class="container-fluid clearfix">
                        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © Tüm Hakları Saklıdır |@DateTime.Now.Year</span>
                        @*<span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">  <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Profil </a> </span>*@
                    </div>
                </footer>

            </div>

        </div>

    </div>

    <script src="~/AdminPage/assets/vendors/js/vendor.bundle.base.js"></script>

    <script src="~/AdminPage/assets/js/off-canvas.js"></script>
    <script src="~/AdminPage/assets/js/hoverable-collapse.js"></script>
    <script src="~/AdminPage/assets/js/misc.js"></script>


</body>
</html>

Kmu.Appointment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Kmu_Appointment</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @* Uncomment to use the HtmlEditor control *@
    @* <script src="https://unpkg.com/devextreme-quill@21_2/dist/dx-quill.min.js"></script> *@

    <link rel="stylesheet" href="~/css/vendor.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Site.css" />
    <script src="~/js/vendor.js" asp-append-version="true"></script>
    <style>
        li a, .dropbtn {
            display: inline-block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

            

        li.dropdown {
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .dropdown-content a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
                text-align: left;
            }

                .dropdown-content a:hover {
                    background-color: #f1f1f1;
                }

        .dropdown:hover .dropdown-content {
            display: block;
        }
    </style>
</head>

<body style="padding-top: 5rem;">

    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <a class="navbar-brand" href="/">Kmu_Appointment</a>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div id="navbar" class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Doktorlar</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Polyclinics" asp-action="Polyclinics">Poliklinikler</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Contact" asp-action="Index">İletişim</a></li>
                
                <li class="nav-item dropdown">
                    <a href="javascript:void(0)" class="nav-link dropbtn">Randevu</a>
                    <div class="dropdown-content">
                        <a href="/Appointment/AddAppointment/">Randevu AL</a>
                        <a href="/Appointment/CancelAppointment/">Randevu İptal</a>
                        
                    </div>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">

                @* <li><a href="#"><span class="glyphicon glyphicon-log-in"></span>Giriş Yap</a></li>*@
                <li class="nav-item"><a class="glyphicon glyphicon-log-in" asp-area="" asp-controller="Login" asp-action="Index">Giriş Yap</a></li>
            </ul>
            
        </div>
    </nav>

    <main role="main" class="container">
        @RenderBody()
    </main>
</body>

</html>